### ISSUE TITLE
Misc Issues Tracker

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-ng#10]
This issue is used to track minor issues, there need to fixed

- [x] #36
- [x] when search is cleared, it does not return to the state before the search was started
- [x] Depencies is not added, when packages is add to queue for delection
- [x] opening sidebar with F9, should set the focus to "installed" for better keyboard navigation
- [x] handle longer progress subtitles so progressbar don't move up and down in placement
