### ISSUE TITLE
Misc feature tracker

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-ng#12]
This issue is kind of a TODO list for features there need to be done in the future

- [x] Create RPM .spec file for building RPM for yumex-ng
- [x] Create Makefile targets for building RPM for current git checkout
- [x] Create .desktop file and install/build script (Meson)
- [x] Create appdata file and install/build script (Meson)
